{{ if .Values.kafka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- range $key, $val := .Values.globalLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
  name: kafka
spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: {{ printf "%s%s" .Values.registryBasePath "kafka:latest" }}
          name: kafka
          ports:
            - containerPort: 12092
          env:      
           - name: KAFKA_ZOOKEEPER_CONNECT
             value: {{ (print .Values.kafka.zookeeperEndpoint ":" .Values.zookeeper.svcPort) | quote }}
          volumeMounts:
            - mountPath: /data
              name: kafka-claim0
      restartPolicy: Always
      volumes:
        - name: kafka-claim0
          persistentVolumeClaim:
            claimName: kafka
{{ end }}