{{ if and .Values.kafka.enabled .Values.kafka.ingressEnabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka
spec:
  defaultBackend:
    service:
      name: kafka
      port:
        number: {{ .Values.kafka.svcPort }}
{{ end }}
