{{ if and .Values.kafka.enabled .Values.kafka.ingressEnabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: kafka
spec:
  podSelector:
    matchLabels:
      app: kafka
  ingress:
  - {}
{{ end }}
