{{ if .Values.telegraf.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- range $key, $val := .Values.globalLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
  name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - image: {{ printf "%s%s" .Values.registryBasePath "telegraf:latest" }}
          name: telegraf
          ports:
            - containerPort: 8125
              protocol: UDP
      restartPolicy: Always
{{ end }}