apiVersion: v2
name: latencetech-analyzer
version: 0.1.0
description: Chart used to deployed the analyzer and its required components.
icon: https://helm.sh/img/helm.svg

dependencies:
- name: ingress-nginx
  condition: deployNginxIngress
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.7.0

### NOTES ###
#
# - The chart doesn't deploy resources quota/requirements, 
#   this should be planed ahead of deployment.
#
# - Permissive network policies will be deployed by this chart. 
#   Required policies should be added to restrict traffic.
#
# - POD identies are not in place should be considered
#
# - Svc to pod issues possibly caused by an explicit bind to pod IP
#
# - InfluxDB stopping with a config error
#
# - InfluxDB could be deployed as a statefulset
#
# - Kafka config should use the zoopeeker service DNS
#
# - Kafka could be deployed as a statefulset (not possible unless clusterIp is removed from service)
#
# - Anomaly init container could be optimized
###
