{{ if .Values.influx.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- range $key, $val := .Values.globalLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - image: {{ printf "%s%s" .Values.registryBasePath "influxdb:latest" }}
          name: influxdb
          ports:
            - containerPort: 8086
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /var/lib/influxdb2
              name: influxdb-claim0
      restartPolicy: Always
      volumes:
        - name: influxdb-claim0
          persistentVolumeClaim:
            claimName: influxdb
{{ end }}
