{{ if .Values.zookeeper.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    {{- range $key, $val := .Values.globalLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
  name: zookeeper
spec:
  replicas: 1
  minReadySeconds: 10
  serviceName: zookeeper
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: {{ printf "%s%s" .Values.registryBasePath "zookeeper:latest" }}
          name: zookeeper
          ports:
            - containerPort: 2181
      restartPolicy: Always
{{ end }}